

<h1 align="center">
    NSDC Data Science Projects
</h1>

<h2 align="center">
    Project: Practicing Writing SQL Queries - #1
</h2>

<h3 align="center">
    Name: Sainofo Fanene
</h3>

In [ ]:
import pandas as pd
import numpy as np
import sqlite3
from google.colab import files

conn = sqlite3.connect('airbnb.db')

uploaded = files.upload()

filename = list(uploaded.keys())[0]

df = pd.read_csv(filename)

df.to_sql('listings', conn, if_exists='replace', index=False)

cursor = conn.cursor()

cursor.execute("SELECT * FROM listings;")

results = cursor.fetchall()

for i, row in enumerate(results[:10]):
    print(row)

cursor.execute("SELECT COUNT(*) FROM listings;")

count = cursor.fetchone()[0]

print("Total number of records in the 'listings' table:", count)

cursor.execute("""
    SELECT neighbourhood_group, neighbourhood, AVG(price) AS avg_price
    FROM listings
    GROUP BY neighbourhood_group, neighbourhood
    ORDER BY avg_price DESC
    LIMIT 10;
""")

results = cursor.fetchall()

for row in results:
    print(row)

cursor.execute("""
    SELECT room_type, COUNT(*) AS num_listings
    FROM listings
    GROUP BY room_type;
""")

results = cursor.fetchall()

for row in results:
    print(row)

cursor.execute("""
     SELECT AVG(number_of_reviews) AS avg_reviews
     FROM listings;
""")


result = cursor.fetchone()

print("Average number of reviews per listing:", result[0])

cursor.execute("""
    SELECT id
    FROM listings
    WHERE number_of_reviews = (SELECT MIN(number_of_reviews) FROM listings)
    LIMIT 15;
""")

results = cursor.fetchall()

for row in results:
    print(row)

cursor.execute("""
    SELECT *
    FROM listings
    WHERE neighbourhood = 'Chelsea' AND price <= 200
""")

results = cursor.fetchall()

for row in results:
    print(row)

cursor.close()
conn.close()

<h3 align = 'center' >
Thank you for completing the project!
</h3>

Please do reach out to us if you have any questions or concerns. We are here to help you learn and grow.

Please send your completed Google Colab Notebook to the NSDC HQ Team at nsdc@nebigdatahub.org in order to receive your virtual certificate of completion.